var __SRC_DIR = "./src";
require(__SRC_DIR+"/css/jquery.fullPage.css");
require(__SRC_DIR+"/css/weui.css");
require(__SRC_DIR+"/css/jquery-weui.css");
require(__SRC_DIR+"/css/SentyZHAO.css");
require(__SRC_DIR+"/css/main.css");
require(__SRC_DIR+"/css/fakeLoader.css");
require(__SRC_DIR+"/css/error.css");
require(__SRC_DIR+"/js/error.js");
require(__SRC_DIR+"/js/global/bgm.js");